FROM ubuntu:16.10

MAINTAINER Dockerfiles

# Install required packages and remove the apt packages cache when done.

RUN apt-get update && apt-get install -y \
    git \
    vim \
    gettext \
    python3 \
    python3-dev \
    python3-setuptools \
    python3-pip \
    nginx \
    supervisor \
    sqlite3 \
    postgresql-client \
    libpq-dev \
    libjpeg8-dev \
  && rm -rf /var/lib/apt/lists/* \
  && mkdir /code


# install uwsgi now because it takes a little while
RUN pip3 install --upgrade pip
RUN pip3 install uwsgi

# setup all the configfiles
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
COPY deployment/deploy_conf/nginx-app.conf /etc/nginx/sites-available/default
COPY deployment/deploy_conf/supervisor-app.conf /etc/supervisor/conf.d/
COPY deployment/deploy_conf/uwsgi_params /etc/nginx/
COPY deployment/deploy_conf/uwsgi.ini /code

WORKDIR /code

COPY requirements/production.txt .
RUN pip3 install -r production.txt

# add (the rest of) our code
COPY ./seats_api /code/
RUN python3 manage.py collectstatic --no-input
EXPOSE 80
CMD supervisord -n
