version: '3'

volumes:
  postgres:
    driver: local

services:
  db:
    image: postgres:9.6
    volumes:
    - "postgres:/var/lib/postgresql/data"

  api:
    image: seats/api
    ports:
    - "80:80"