version: '3'
volumes:
    dev_seats_postgres:
        driver: local

services:
  db:
    image: postgres:9.6
    volumes:
    - "dev_seats_postgres:/var/lib/postgresql/data"
    ports:
    - "5432:5432"