# Generated by Django 2.0.1 on 2018-01-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_auto_20180120_1323'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('reason', models.CharField(max_length=256, verbose_name='reason')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_seats', to='events.Event')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.Seat')),
            ],
        ),
    ]
