# Generated by Django 2.0.1 on 2018-01-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('row', models.PositiveIntegerField(verbose_name='row location')),
                ('column', models.PositiveIntegerField(verbose_name='colunm location')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('rows', models.PositiveIntegerField(verbose_name='number of rows')),
                ('columns', models.PositiveIntegerField(verbose_name='number of columns')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='venues.Venue'),
        ),
        migrations.AddField(
            model_name='seat',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.Section'),
        ),
    ]
